GAP-2423: Upgrade dependencies
cabinetoffice/gap-find-web pull request #126
Opened 2024-02-07 15:35 UTC by ryan-tco

## Description

Upgrades dependencies identified by snyk

Ticket # and link

[GAP-2423](https://technologyprogramme.atlassian.net/jira/software/projects/GAP/boards/216?selectedIssue=GAP-2423)

Summary of the changes and the related issue. List any dependencies that are required for this change:

## Type of change

Please check the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes:

- [x] Unit Test

2024-02-07 16:47 UTC, dominicwest requested changes

2024-02-07 16:47 UTC, dominicwest commented on .snyk
> +      expires: 2024-03-01T00:00:46.319Z
```suggestion
      expires: 2024-04-01T00:00:46.319Z
```

2024-02-07 16:47 UTC, dominicwest commented on .snyk
> +      expires: 2024-03-08T15:43:03.411Z
```suggestion
      expires: 2024-04-01T15:43:03.411Z
```

2024-02-07 16:47 UTC, dominicwest commented on .snyk
> +      expires: 2024-03-08T15:43:45.894Z
```suggestion
      expires: 2024-04-01T15:43:45.894Z
```

2024-02-12 16:46 UTC, ConorFayleTCO approved these changes

2024-02-13 10:04 UTC, merged